version: '3'

services:
    nginx:
        container_name: Nginx
        
        image: nginx:stable-alpine
        restart: unless-stopped
        
        networks:
            extnetwork:
                ipv4_address: 172.20.1.1
        
        volumes:
            - /home/nginx/conf.d:/etc/nginx/conf.d

        ports:
            - '80:80'
            - '443:443'


    portainer:
        container_name: Portainer
        
        image: portainer/portainer-ce:latest
        restart: unless-stopped
        
        networks:
            extnetwork:
                ipv4_address: 172.20.1.2

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/portainer:/data

        #ports:
        #    - '9000:9000'


    postgres10:
        container_name: Postgres10

        image: postgres:10-alpine
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.1.3

        volumes:
            - /home/postgresql/data:/var/lib/postgresql/data

        environment:
            POSTGRES_PASSWORD: password

        ports:
            - '5432:5432'
    

    confluence:
        container_name: Confluence
        user: '2002:2002'

        image: atlassian/confluence-server
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.1.4

        volumes:
            - /home/confluence:/var/atlassian/application-data/confluence

        environment:
            - JVM_MINIMUM_MEMORY=1024m
            - JVM_MAXIMUM_MEMORY=32768m
        
            - ATL_PROXY_NAME=wiki.zchd.com
            - ATL_PROXY_PORT=80
            
            - JAVA_OPTS="-javaagent:/var/atlassian/application-data/confluence/atlassian-agent.jar"
            #- JVM_SUPPORT_RECOMMENDED_ARGS="-Datlassian.recovery.password=0o0o0o0o0o0o0o0000o0o"

        ports:
            - '8090:8090'
            - '8091:8091'


    gitlab:
        container_name: Gitlab

        image: gitlab/gitlab-ce:latest
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.1.5

        volumes:
            - /home/gitlab/config:/etc/gitlab
            - /home/gitlab/log:/var/log/gitlab
            - /home/gitlab/data:/var/opt/gitlab

        ports:
            - '2022:22'
            #- '20080:80'
            #- '20443:443'


#    grafana:
#        container_name: Grafana
#        user: '472:472'
#
#        image: grafana/grafana
#        restart: unless-stopped
#
#        networks:
#            extnetwork:
#                ipv4_address: 172.20.1.6
#        
#        volumes:
#            - /home/grafana:/var/lib/grafana
#
#        #ports:
#        #    - 3000:3000

    
#    prometheus:
#        container_name: Prometheus
#
#        image: prom/prometheus
#        restart: unless-stopped
#
#        networks:
#            extnetwork:
#                ipv4_address: 172.20.1.7
#        
#        volumes:
#            - /home/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#
#        ports:
#            - 9090:9090



networks:
    extnetwork:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
