version: '3'

services:
    
    portainer:
        container_name: Portainer
        
        image: portainer/portainer:latest
        restart: unless-stopped
        
        networks:
            extnetwork:
                ipv4_address: 172.20.0.2

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/portainer:/data

        #ports:
        #    - '9000:9000'


    
    
    postgres96:
        container_name: Postgres96

        image: postgres:9.6
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.0.3

        volumes:
            - /home/postgresql/data:/var/lib/postgresql/data

        environment:
            POSTGRES_PASSWORD: password

        ports:
            - '5432:5432'
    
    
    
    mongo:
        container_name: MongoDB
                
        image: mongo:latest
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.0.4
        
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

        volumes:
            - /home/mongo/db:/data/db
            - /home/mongo/configdb:/data/configdb

        ports:
            - '27017:27017'



    nginx:
        container_name: Nginx
        
        image: nginx:latest
        restart: unless-stopped
        
        networks:
            extnetwork:
                ipv4_address: 172.20.0.5
        
        volumes:
            - /home/nginx/conf.d:/etc/nginx/conf.d
        
        ports:
            - '80:80'
            - '443:443'




    jira:
        container_name: Jira_ServiceDesk
        user: '2001:2001'

        image: atlassian/jira-servicedesk
        restart: unless-stopped

        depends_on:
            - postgres96

        networks:
            extnetwork:
                ipv4_address: 172.20.0.6

        volumes:
            - /home/jira:/var/atlassian/application-data/jira

        environment:
            - JVM_MINIMUM_MEMORY=1024m
            - JVM_MAXIMUM_MEMORY=16384m

            - ATL_PROXY_NAME=jira.ds.com
            - ATL_PROXY_PORT=80

        #ports:
        #    - '8080:8080'



    confluence:
        container_name: Confluence
        user: '2002:2002'

        image: atlassian/confluence-server:latest
        restart: unless-stopped

        depends_on:
            - postgres96

        networks:
            extnetwork:
                ipv4_address: 172.20.0.7

        volumes:
            - /home/confluence:/var/atlassian/application-data/confluence

        environment:
            - JVM_MINIMUM_MEMORY=1024m
            - JVM_MAXIMUM_MEMORY=16384m
        
            - ATL_PROXY_NAME=wiki.ds.com
            - ATL_PROXY_PORT=80

        ports:
            - '8090:8090'
            - '8091:8091'



    gitlab:
        container_name: Gitlab

        image: gitlab/gitlab-ce:latest
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.0.9

        volumes:
            - /home/gitlab/config:/etc/gitlab
            - /home/gitlab/log:/var/log/gitlab
            - /home/gitlab/data:/var/opt/gitlab

        ports:
            - '2022:22'
            #- '20080:80'
            #- '20443:443'


    

    rabbitmq:
        container_name: RabbitMQ
        
        image: rabbitmq:3.8.2-management
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.0.10
        
        volumes:
            - /home/rabbitmq/data:/var/lib/rabbitmq

        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password

        ports:
            - '5672:5672'
            - '15672:15672'


    
    
    netdata:
        container_name: NetData
        
        image: netdata/netdata
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.0.11
        
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        
        cap_add:
            - SYS_PTRACE
        
        security_opt:
            - apparmor:unconfined

        #ports:
        #    - '19999:19999'


    mongo-express:
        container_name: MongoExpress

        image: mongo-express
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.0.12

        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

        #ports:
        #    - 8081:8081



    filebrowser:
        container_name: FileBrowser

        image: filebrowser/filebrowser
        restart: unless-stopped

        networks:
            extnetwork:
                ipv4_address: 172.20.0.13
        
        volumes:
            - /home/filebrowser/config.json:/etc/config.json
            - /home/filebrowser/database.db:/etc/database.db
            - /mnt:/srv

        #ports:
        #    - 80:80
        

    shotgun-event:
        container_name: ShotgunEvent

        image: shotgun-event
        restart: unless-stopped


        networks:
            extnetwork:
                ipv4_address: 172.20.0.14

        volumes:
            - /home/pipeline/shotgunEventDaemon:/home/pipeline/shotgunEventDaemon
            - /home/pipeline/shotgunEventDaemon/shotgunEvents/src/:/usr/src/myapp

        working_dir: /usr/src/myapp

        entrypoint: ["python", "shotgunEventDaemon.py", "foreground"]



networks:
    extnetwork:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
